apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: kushil001/petsclinic:1.0
        ports:
        - containerPort: 8080
        env:  
          - name: DB_HOST   
            valueFrom:
              configMapKeyRef:
                 name: db-config
                 key:  host
          - name: DB_NAME  
            valueFrom:
              configMapKeyRef:
                 name: db-config
                 key:  dbName
          - name: DB_USERNAME  
            valueFrom:
              configMapKeyRef:
                 name: db-config
                 key:  user
          - name: DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                 name: mysql-secret
                 key:  password

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  selector:
    app: petclinic
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30004
